(* test/config/test_config.ml *)

open Alcotest
open Dio_types                           (* root module of dio.types *)

(* ------------------------------------------------------------------ *)
(* Helper: JSON round-trip using the _exn helpers generated by ppx_deriving *)
let json_round_trip_exn ~pp_json to_json of_json_exn v =
  let j  = to_json v in
  let v' = of_json_exn j in
  check (testable pp_json (=)) "json round-trip" j (to_json v')

(* ------------------------------------------------------------------ *)
let asset_cfg_sample =
  let open Primitives in
  { Config.symbol        = "BTC/USD"
  ; qty                  = Qty.of_string_exn   ~scale:8 "0.01000000"
  ; grid_interval        = Some (Fixed.of_string_exn ~scale:8 "1.0") (* Represents 1% *)
  ; sell_mult            = Some (Fixed.of_string_exn ~scale:8 "0.999")
  ; min_usd_balance      = None
  ; strategy             = Config.Grid
  }

let runtime_cfg_sample =
  { Config.assets      = [ asset_cfg_sample ]
  ; queues_cap         = 64
  ; profit_threshold_pct = 0.0010
  }

(* ------------------------------------------------------------------ *)
let test_asset_cfg () =
  json_round_trip_exn
    ~pp_json:Yojson.Safe.pp
    Config.asset_cfg_to_yojson
    Config.asset_cfg_of_yojson_exn
    asset_cfg_sample

let test_runtime_cfg () =
  json_round_trip_exn
    ~pp_json:Yojson.Safe.pp
    Config.runtime_cfg_to_yojson
    Config.runtime_cfg_of_yojson_exn
    runtime_cfg_sample

(* ------------------------------------------------------------------ *)
let () =
  run "Config"
    [ "JSON",
      [ test_case "asset_cfg"   `Quick test_asset_cfg
      ; test_case "runtime_cfg" `Quick test_runtime_cfg
      ]
    ]
