(* generated by dune *)

(** @canonical Caqti_platform_unix.Driver_loader *)
module Driver_loader = Caqti_platform_unix__Driver_loader

(** @canonical Caqti_platform_unix.System_sig *)
module System_sig = Caqti_platform_unix__System_sig
