opam-version: "2.0"
name: "dio"
version: "0.0.0"

maintainer: "malciller@gmail.com"
authors:     "Cal Miller"
license:     "MIT"
homepage:    "https://github.com/malciller/dio"
dev-repo:    "git+https://github.com/malciller/dio.git"
bug-reports: "https://github.com/malciller/dio/issues"

synopsis: "Trading engine"

depends: [
  "ocaml"              {>= "4.14" & < "5.0"}  
  "dune"               {>= "3.13"}
  "lwt"  "lwt_ppx"
  "yojson"  "ppx_deriving_yojson"
  "decimal"
  "caqti"  "caqti-driver-sqlite3"
  "websocket-lwt"                      
  "cmdliner"
  "alcotest"
  "prometheus"
]

build: [
  ["dune" "build" "-p" name "-j" jobs]
]
