(library
 (name engine_strategy)
 (public_name dio.engine.strategy)
 (modules kraken_suicide_grid kraken_top_level_mm kraken_arbitrage)
 (libraries
  dio.dio_types
  dio.state
  dio.engine
  lwt
  yojson
  cohttp-lwt-unix
  cmdliner
  dio.exchange.kraken)
 (preprocess
  (pps lwt_ppx))
 (wrapped false))
