opam-version: "2.0"
lib: [
  "_build/opam" {"opam"}
  "_build/pkg/META" {"META"}
  "_build/src/asetmap.a" {"asetmap.a"}
  "_build/src/asetmap.cma" {"asetmap.cma"}
  "_build/src/asetmap.cmi" {"asetmap.cmi"}
  "?_build/src/asetmap.cmti" {"asetmap.cmti"}
  "_build/src/asetmap.cmx" {"asetmap.cmx"}
  "_build/src/asetmap.cmxa" {"asetmap.cmxa"}
  "_build/src/asetmap.cmxs" {"asetmap.cmxs"}
  "_build/src/asetmap.mli" {"asetmap.mli"}
]
doc: [
  "_build/CHANGES.md" {"CHANGES.md"}
  "_build/LICENSE.md" {"LICENSE.md"}
  "_build/README.md" {"README.md"}
]
