opam-version: "2.0"
lib: [
  "_build/install/default/lib/caqti-driver-sqlite3/META"
  "_build/install/default/lib/caqti-driver-sqlite3/caqti_driver_sqlite3.a"
  "_build/install/default/lib/caqti-driver-sqlite3/caqti_driver_sqlite3.cma"
  "_build/install/default/lib/caqti-driver-sqlite3/caqti_driver_sqlite3.cmi"
  "_build/install/default/lib/caqti-driver-sqlite3/caqti_driver_sqlite3.cmt"
  "_build/install/default/lib/caqti-driver-sqlite3/caqti_driver_sqlite3.cmti"
  "_build/install/default/lib/caqti-driver-sqlite3/caqti_driver_sqlite3.cmx"
  "_build/install/default/lib/caqti-driver-sqlite3/caqti_driver_sqlite3.cmxa"
  "_build/install/default/lib/caqti-driver-sqlite3/caqti_driver_sqlite3.ml"
  "_build/install/default/lib/caqti-driver-sqlite3/caqti_driver_sqlite3.mli"
  "_build/install/default/lib/caqti-driver-sqlite3/dune-package"
  "_build/install/default/lib/caqti-driver-sqlite3/opam"
]
doc: [
  "_build/install/default/doc/caqti-driver-sqlite3/CHANGES.md"
  "_build/install/default/doc/caqti-driver-sqlite3/README.md"
]
libexec:
  "_build/install/default/lib/caqti-driver-sqlite3/caqti_driver_sqlite3.cmxs"
