opam-version: "2.0"
lib: [
  "_build/install/default/lib/prometheus/META"
  "_build/install/default/lib/prometheus/dune-package"
  "_build/install/default/lib/prometheus/opam"
  "_build/install/default/lib/prometheus/prometheus.a"
  "_build/install/default/lib/prometheus/prometheus.cma"
  "_build/install/default/lib/prometheus/prometheus.cmi"
  "_build/install/default/lib/prometheus/prometheus.cmt"
  "_build/install/default/lib/prometheus/prometheus.cmti"
  "_build/install/default/lib/prometheus/prometheus.cmx"
  "_build/install/default/lib/prometheus/prometheus.cmxa"
  "_build/install/default/lib/prometheus/prometheus.ml"
  "_build/install/default/lib/prometheus/prometheus.mli"
]
doc: [
  "_build/install/default/doc/prometheus/CHANGES.md"
  "_build/install/default/doc/prometheus/LICENSE.md"
  "_build/install/default/doc/prometheus/README.md"
]
libexec: "_build/install/default/lib/prometheus/prometheus.cmxs"
