opam-version: "2.0"
lib: [
  "_build/install/default/lib/sqlite3/META"
  "_build/install/default/lib/sqlite3/dune-package"
  "_build/install/default/lib/sqlite3/libsqlite3_stubs.a"
  "_build/install/default/lib/sqlite3/opam"
  "_build/install/default/lib/sqlite3/sqlite3.a"
  "_build/install/default/lib/sqlite3/sqlite3.cma"
  "_build/install/default/lib/sqlite3/sqlite3.cmi"
  "_build/install/default/lib/sqlite3/sqlite3.cmt"
  "_build/install/default/lib/sqlite3/sqlite3.cmti"
  "_build/install/default/lib/sqlite3/sqlite3.cmx"
  "_build/install/default/lib/sqlite3/sqlite3.cmxa"
  "_build/install/default/lib/sqlite3/sqlite3.ml"
  "_build/install/default/lib/sqlite3/sqlite3.mli"
]
stublibs: "_build/install/default/lib/stublibs/dllsqlite3_stubs.so"
doc: [
  "_build/install/default/doc/sqlite3/CHANGELOG.md"
  "_build/install/default/doc/sqlite3/LICENSE.md"
  "_build/install/default/doc/sqlite3/README.md"
]
libexec: "_build/install/default/lib/sqlite3/sqlite3.cmxs"
