(library
 (name kraken)
 (public_name dio.exchange.kraken)
 (modules
  kraken_common_types
  kraken_balances
  kraken_fee_cache
  kraken_generate_auth_token
  kraken_incoming_data
  kraken_outgoing_data
  kraken_orderbook)
 (preprocess
  (pps ppx_deriving_yojson lwt_ppx))
 (libraries
  dio.state
  dio.dio_types
  dio.notification.discord_webhook
  lwt
  lwt.unix
  websocket-lwt-unix
  cohttp-lwt-unix
  yojson
  uri
  logs
  digestif
  base64
  dotenv
  mirage-crypto
  cstruct
  conduit-lwt-unix))
