(library
 (name kraken)
 (public_name dio.exchange.kraken)
 (modules common token ws_feed kraken_exec)
 (preprocess (pps ppx_deriving_yojson lwt_ppx))
 (libraries
  dio.state
  dio.dio_types
  lwt
  lwt.unix
  websocket-lwt-unix
  cohttp-lwt-unix
  yojson
  uri
  logs
  digestif
  base64
  dotenv
  mirage-crypto
  cstruct
  conduit-lwt-unix
  dio.database))
