(* generated by dune *)

(** @canonical Caqti_platform.Connection_utils *)
module Connection_utils = Caqti_platform__Connection_utils

(** @canonical Caqti_platform.Connector *)
module Connector = Caqti_platform__Connector

(** @canonical Caqti_platform.Conv *)
module Conv = Caqti_platform__Conv

(** @canonical Caqti_platform.Driver_loader *)
module Driver_loader = Caqti_platform__Driver_loader

(** @canonical Caqti_platform.Heap *)
module Heap = Caqti_platform__Heap

(** @canonical Caqti_platform.List_ext *)
module List_ext = Caqti_platform__List_ext

(** @canonical Caqti_platform.Logging *)
module Logging = Caqti_platform__Logging

(** @canonical Caqti_platform.Pool *)
module Pool = Caqti_platform__Pool

(** @canonical Caqti_platform.Request_utils *)
module Request_utils = Caqti_platform__Request_utils

(** @canonical Caqti_platform.Stream *)
module Stream = Caqti_platform__Stream

(** @canonical Caqti_platform.Switch *)
module Switch = Caqti_platform__Switch

(** @canonical Caqti_platform.System_sig *)
module System_sig = Caqti_platform__System_sig
