name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '4.14.2'
          dune-cache: true

      # --- system packages & opam deps ----
      - name: apt-get update (non-interactive)
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update -y

      - name: Install Linux depexts
        run: opam depext -iy --with-test .

      - name: Install project deps
        run: opam install . --deps-only --with-test -y

      # --- build & tests -------------------
      - name: Build
        run: dune build @all

      - name: Run tests
        run: dune runtest
