name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # OCaml tool-chain + dune cache
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '4.14.2'
          dune-cache: true

      # --- Install system packages & opam deps ------------------------------
      - name: Install Linux depexts
        run: opam depext -iy --with-test .

      - name: Install project deps
        run: opam install . --deps-only --with-test -y

      # --- Build & test ------------------------------------------------------
      - name: Build
        run: dune build @all

      - name: Run tests
        run: dune runtest
